create table member
(
    id            bigint generated by default as identity,
    role          varchar(255) not null,
    team_id       bigint       not null,
    user_id       bigint       not null,
    creator       smallint(1) not null,
    participation smallint (1) not null,
    primary key (id)
);
create table project
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table team
(
    id               bigint generated by default as identity,
    end_time         timestamp,
    location         varchar(255),
    max_member_count bigint not null,
    start_time       timestamp,
    status           varchar(255),
    project_id       bigint,
    subject          varchar(255),
    description      clob,
    primary key (id)
);
create table user
(
    id       bigint generated by default as identity,
    email    varchar(255) not null,
    fullname varchar(255) not null,
    nickname varchar(255) not null,
    picture  varchar(255),
    role     varchar(255) not null,
    primary key (id)
);
create table review
(
    id          bigint generated by default as identity,
    team_id     bigint,
    user_id     bigint,
    description varchar(300),
    fun         int,
    interested  int,
    nice        int,
    time        int,
    status      varchar(255) not null,
    created     timestamp,
    updated     timestamp,
    primary key (id)
);

alter table member
    add constraint FK_MEMBER_TEAM foreign key (team_id) references team;
alter table member
    add constraint FK_MEMBER_USER foreign key (user_id) references user;
alter table team
    add constraint FK_TEAM_PROJECT foreign key (project_id) references project;
alter table review
    add constraint FK_REVIEW_TEAM foreign key (team_id) references team;
alter table review
    add constraint FT_REVIEW_USER foreign key (user_id) references user;