# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: remote ssh command for dev deploy
on:
  push:
    # develop 브랜치에서만 작동합니다.
    branches: [develop]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
#  pull_request:
#    branches: [main]
#    paths-ignore:
#      - 'README.md'
#      - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd git/helper-dev/scripts
            sh deploy.sh
